#!/bin/sh

# List all files that are useful for grepping within my website.

echo "Note: 0paperlined_all doesn't currently include any files from paperlined.org/tmp/"  >&2
echo "or any of the private directories. Use 0paperlined_allall if that's an issue."       >&2

# This should *not* end in a slash.
ROOT=/var/www/paperlined.org

find "$ROOT" -type f \
        \( -iname '*.md' -or -iname '*.html' \) \
        -not \( \
            -path     "$ROOT/recent.html.gz" \
            -or -path "$ROOT/recent.html" \
            -or -path "$ROOT/index.html" \
            -or -path "$ROOT/.index_filelist" \
            -or -path "$ROOT/m/recent.html" \
            -or -path "$ROOT/private/recent.html" \
            -or -path "$ROOT/private/recent.html.gz" \
            -or -path "$ROOT/documentation.html" \
        \) -print0 \
    | perl -0e 'print join chr(0), sort {-M $b <=> -M $a} map {chomp; $_} <>'
                                       #  ^^^^^^^^^^^^^^  by default, sort with the most recently
                                       #                modified files last
