#!/usr/bin/bash

## Do a health-check using curl, to try to contact our own webserver. If it seems to be
## unresponsive, then restart it.
##
## The intent here is to call this from a cron script.


## To install this, add this to root's cron:
##
##      0,10,20,30,40,50 * * * *    /var/www/wsgi/utilties/restart_apache_if_uncontactable >> /var/log/cron.restart_apache_if_uncontactable.log 2>&1


            # a 3 second timeout for localhost should be *plenty*
curl --max-time 3 \
    --silent --show-error --fail \
    https://paperlined.org/ \
        > /dev/null

if [ "$?" -ne 0 ]; then
    echo "$(date) -- Restarting."
    sudo apachectl restart
else
    echo "$(date) -- All good."
fi
